### ISSUE TITLE
Feature Request: Support use of iam-role with ConnectionManager

### ISSUE THREAD

**Issue by SpyderDave** [Sceptre/sceptre-ssm-resolver#13]
Currently, it appears as though the SSM Resolver has a hard coded use of _profile_  (https://github.com/Sceptre/sceptre-ssm-resolver/blob/master/resolver/ssm.py#L60)

I am not familiar with the code in this project so I am looking for a little assistance in supporting the use of iam_role from the ConnectionManager (https://github.com/Sceptre/sceptre/blob/master/sceptre/connection_manager.py#L259)

**Comment by zaro0508** [comment]
> Currently, it appears as though the SSM Resolver has a hard coded use of profile (https://github.com/Sceptre/sceptre-ssm-resolver/blob/master/resolver/ssm.py#L60)

You can [assume a role with profile](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_profiles.html#assume-role-with-profile) then tell the this resolver to use whichever profile you like, the README has an example of specifying profiles.

> I am not familiar with the code in this project so I am looking for a little assistance in supporting the use of iam_role from the ConnectionManager (https://github.com/Sceptre/sceptre/blob/master/sceptre/connection_manager.py#L259)

If you prefer to support iam_role env vars then maybe sceptre PR https://github.com/Sceptre/sceptre/pull/1287 will help?

**Comment by jfalkenstein** [comment]
This issue should be resolved with https://github.com/Sceptre/sceptre/issues/1299

**Comment by zaro0508** [comment]
related to https://github.com/Sceptre/sceptre/pull/1300
