### ISSUE TITLE
Feature request: specify a optional AWS profile to connect to a different account/region

### ISSUE THREAD

**Issue by RolandOtta** [Sceptre/sceptre-ssm-resolver#5]
Hi,

thank you for providing this useful resolver.

it would be great to have to possibility to provide an optional aws profile, for fetching parameters from a different account (like it is possible with the stack_output_external resolver https://sceptre.cloudreach.com/2.4.0/docs/resolvers.html#stack-output-external)

**Comment by nathan-williams-rozettatechnology** [comment]
I would like to use this new feature, but PyPi only has version 1.1.0 available.
When can I expect a release of 1.1.1?

Thanks

**Comment by zaro0508** [comment]
@nathan-williams-rozettatechnology it will not be available on pypi until the sceptre build is fixed, https://github.com/Sceptre/sceptre/discussions/964

In the mean time you can pip install directly from github, `pip install git+git://github.com/Sceptre/sceptre-ssm-resolver.git`
